/**
 * ActorDesigner frontend tests — covers creation, generation, and session navigation.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import type { ReactNode } from 'react';

// Mock the API client
vi.mock('@/lib/api-client', () => ({
  default: {
    get: vi.fn(),
    post: vi.fn(),
    patch: vi.fn(),
  },
}));

// Mock GenerationStatus
vi.mock('@/components/GenerationStatus', () => ({
  default: function MockGenerationStatus({ status }: { status: string }) {
    return <div data-testid="generation-status">{status}</div>;
  },
}));

// Mock ReferenceImageUpload
vi.mock('@/components/ReferenceImageUpload', () => ({
  default: function MockReferenceImageUpload() {
    return <div data-testid="reference-image-upload">Reference Upload</div>;
  },
}));

// Mock ActorFormFields
vi.mock('@/components/ActorFormFields', () => ({
  default: function MockActorFormFields() {
    return <div data-testid="actor-form-fields">Form Fields</div>;
  },
}));

// Mock PageContainer and PageHeader
vi.mock('@/components/layout/PageContainer', () => ({
  default: function MockPageContainer({ children }: { children: ReactNode }) {
    return <div data-testid="page-container">{children}</div>;
  },
}));

vi.mock('@/components/layout/PageHeader', () => ({
  default: function MockPageHeader({
    title,
    description,
  }: {
    title: string;
    description?: string;
  }) {
    return (
      <div>
        <h1 data-testid="page-header">{title}</h1>
        {description && <p data-testid="page-description">{description}</p>}
      </div>
    );
  },
}));

// Mock useUnsavedChanges
vi.mock('@/hooks/useUnsavedChanges', () => ({
  useUnsavedChanges: vi.fn(),
}));

import apiClient from '@/lib/api-client';
import ActorDesigner from '@/pages/actors/ActorDesigner';

function createTestQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: 0 },
    },
  });
}

function renderDesigner() {
  const queryClient = createTestQueryClient();
  return render(
    <QueryClientProvider client={queryClient}>
      <MemoryRouter>
        <ActorDesigner />
      </MemoryRouter>
    </QueryClientProvider>,
  );
}

beforeEach(() => {
  vi.clearAllMocks();
  (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
    data: { id: 'actor-123' },
  });
});

/* ================================================================
 * Stage 1: Entry Method Selection
 * ================================================================ */

describe('ActorDesigner — Stage 1: Entry Method Selection', () => {
  it('renders the New Actor page header', () => {
    renderDesigner();
    expect(screen.getByTestId('page-header')).toHaveTextContent('New Actor');
  });

  it('renders all three entry method options', () => {
    renderDesigner();
    expect(screen.getByText('Structured Form')).toBeInTheDocument();
    expect(screen.getByText('Reference Photo')).toBeInTheDocument();
    expect(screen.getByText('Raw Text')).toBeInTheDocument();
  });

  it('defaults to FORM entry method selected', () => {
    renderDesigner();
    expect(screen.getByText('Randomize identity')).toBeInTheDocument();
  });

  it('shows prompt textarea when TEXT method is selected', async () => {
    const user = userEvent.setup();
    renderDesigner();

    // The prompt textarea is hidden when FORM is default
    expect(screen.queryByPlaceholderText(/Describe your actor/i)).not.toBeInTheDocument();

    // shadcn/base-ui RadioGroup: the actual input is aria-hidden with autogenerated id.
    // We find it by name+value since the visual span has the method id.
    const textRadioInput = document.querySelector(
      'input[name*="radio"][value="TEXT"], input[value="TEXT"]',
    ) as HTMLInputElement;
    expect(textRadioInput).not.toBeNull();
    fireEvent.click(textRadioInput);

    // Now the prompt textarea should appear
    await waitFor(() => {
      expect(screen.getByPlaceholderText(/Describe your actor/i)).toBeInTheDocument();
    });
  });

  it('shows randomize checkbox for FORM and TEXT but not REFERENCE', async () => {
    const user = userEvent.setup();
    renderDesigner();

    // FORM is default — randomize visible
    expect(screen.getByText('Randomize identity')).toBeInTheDocument();

    // Click REFERENCE via label[for]
    const refLabel = document.querySelector('label[for="method-REFERENCE"]') as HTMLLabelElement;
    expect(refLabel).not.toBeNull();
    await user.click(refLabel);

    await waitFor(() => {
      expect(screen.queryByText('Randomize identity')).not.toBeInTheDocument();
    });

    // Click FORM
    const formLabel = document.querySelector('label[for="method-FORM"]') as HTMLLabelElement;
    await user.click(formLabel);
    expect(screen.getByText('Randomize identity')).toBeInTheDocument();

    // Click TEXT
    const textLabel2 = document.querySelector('label[for="method-TEXT"]') as HTMLLabelElement;
    await user.click(textLabel2);
    expect(screen.getByText('Randomize identity')).toBeInTheDocument();
  });

  it('renders the Continue button', () => {
    renderDesigner();
    expect(screen.getByRole('button', { name: /continue/i })).toBeInTheDocument();
  });

  it('disables Continue button and shows loading state while creating', async () => {
    const user = userEvent.setup();

    let resolveCreate: (value: { data: { id: string } }) => void;
    (apiClient.post as ReturnType<typeof vi.fn>).mockImplementation(
      () =>
        new Promise((resolve) => {
          resolveCreate = resolve;
        }),
    );

    renderDesigner();

    const continueButton = screen.getByRole('button', { name: /continue/i });
    await user.click(continueButton);

    expect(continueButton).toBeDisabled();

    resolveCreate!({ data: { id: 'actor-456' } });

    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });
  });

  it('shows error message when actor creation fails', async () => {
    const user = userEvent.setup();
    (apiClient.post as ReturnType<typeof vi.fn>).mockRejectedValue({
      message: 'Network error: server unreachable',
    });

    renderDesigner();
    await user.click(screen.getByRole('button', { name: /continue/i }));

    await waitFor(() => {
      expect(screen.getByText('Network error: server unreachable')).toBeInTheDocument();
    });
  });
});

/* ================================================================
 * Stage 2: Generation & Layout Stepper
 * ================================================================ */

describe('ActorDesigner — Stage 2: Generation & Layout Stepper', () => {
  async function goToStage2() {
    const user = userEvent.setup();
    renderDesigner();
    await user.click(screen.getByRole('button', { name: /continue/i }));
    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });
    return user;
  }

  it('shows the 3-step layout stepper (Headshot, Fullshot, Expressions)', async () => {
    await goToStage2();
    // Each step name appears in the stepper button AND in the heading
    const headshotElements = screen.getAllByText('Headshot');
    expect(headshotElements.length).toBeGreaterThanOrEqual(2);
    expect(screen.getByText('Fullshot')).toBeInTheDocument();
    expect(screen.getByText('Expressions')).toBeInTheDocument();
  });

  it('shows step indicator with step number', async () => {
    await goToStage2();
    expect(screen.getByText(/step 1 of 3/i)).toBeInTheDocument();
  });

  it('renders 4 placeholder option cards for image selection', async () => {
    await goToStage2();
    // The ImageGrid renders 4 Card components in a grid.
    // Each card has a relative aspect-square div container.
    // We find the grid container by looking for the element with grid-cols-2 class
    const gridContainer = document.querySelector('[class*="grid-cols-2"]');
    expect(gridContainer).not.toBeNull();
    // The grid should have 4 child divs (the cards)
    const cards = gridContainer!.querySelectorAll('[class*="overflow-hidden"]');
    expect(cards.length).toBe(4);
  });

  it('shows Generate button for the first layout step', async () => {
    await goToStage2();
    expect(screen.getByRole('button', { name: /generate/i })).toBeInTheDocument();
  });

  it('advances to next step when Confirm is clicked after generation', async () => {
    const user = await goToStage2();

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: {
        outputs: [
          { id: 'out-1', image_url: 'http://example.com/1.jpg', status: 'SUCCESS' },
          { id: 'out-2', image_url: 'http://example.com/2.jpg', status: 'SUCCESS' },
          { id: 'out-3', image_url: 'http://example.com/3.jpg', status: 'SUCCESS' },
          { id: 'out-4', image_url: 'http://example.com/4.jpg', status: 'SUCCESS' },
        ],
      },
    });

    await user.click(screen.getByRole('button', { name: /generate/i }));

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /confirm selection/i })).toBeInTheDocument();
    });

    // Select first option
    const firstOption = screen.getAllByRole('img', { name: /generated option/i })[0];
    const cardDiv = firstOption.closest('[class*="cursor-pointer"]') as HTMLElement;
    await user.click(cardDiv);

    await user.click(screen.getByRole('button', { name: /confirm selection/i }));

    await waitFor(() => {
      expect(screen.getByText(/step 2 of 3/i)).toBeInTheDocument();
    });
  });

  it('shows Regenerate button after images are generated', async () => {
    const user = await goToStage2();

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: {
        outputs: [
          { id: 'out-1', image_url: 'http://example.com/1.jpg', status: 'SUCCESS' },
          { id: 'out-2', image_url: 'http://example.com/2.jpg', status: 'SUCCESS' },
          { id: 'out-3', image_url: 'http://example.com/3.jpg', status: 'SUCCESS' },
          { id: 'out-4', image_url: 'http://example.com/4.jpg', status: 'SUCCESS' },
        ],
      },
    });

    await user.click(screen.getByRole('button', { name: /generate/i }));

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /regenerate/i })).toBeInTheDocument();
    });
  });

  it('advances to Stage 3 after confirming the last layout step', async () => {
    const user = await goToStage2();

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: {
        outputs: [
          { id: 'out-1', image_url: 'http://example.com/1.jpg', status: 'SUCCESS' },
          { id: 'out-2', image_url: 'http://example.com/2.jpg', status: 'SUCCESS' },
          { id: 'out-3', image_url: 'http://example.com/3.jpg', status: 'SUCCESS' },
          { id: 'out-4', image_url: 'http://example.com/4.jpg', status: 'SUCCESS' },
        ],
      },
    });

    // Headshot
    await user.click(screen.getByRole('button', { name: /generate/i }));
    await waitFor(() => {
      expect(screen.getByRole('button', { name: /confirm selection/i })).toBeInTheDocument();
    });
    let options = screen.getAllByRole('img', { name: /generated option/i });
    await user.click(options[0].closest('[class*="cursor-pointer"]') as HTMLElement);
    await user.click(screen.getByRole('button', { name: /confirm selection/i }));

    // Fullshot
    await waitFor(() => {
      expect(screen.getByText(/step 2 of 3/i)).toBeInTheDocument();
    });
    await user.click(screen.getByRole('button', { name: /generate/i }));
    await waitFor(() => {
      expect(screen.getByRole('button', { name: /confirm selection/i })).toBeInTheDocument();
    });
    options = screen.getAllByRole('img', { name: /generated option/i });
    await user.click(options[0].closest('[class*="cursor-pointer"]') as HTMLElement);
    await user.click(screen.getByRole('button', { name: /confirm selection/i }));

    // Expressions
    await waitFor(() => {
      expect(screen.getByText(/step 3 of 3/i)).toBeInTheDocument();
    });
    await user.click(screen.getByRole('button', { name: /generate/i }));
    await waitFor(() => {
      expect(screen.getByRole('button', { name: /confirm selection/i })).toBeInTheDocument();
    });
    options = screen.getAllByRole('img', { name: /generated option/i });
    await user.click(options[0].closest('[class*="cursor-pointer"]') as HTMLElement);
    await user.click(screen.getByRole('button', { name: /confirm selection/i }));

    // Stage 3
    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Name your actor and set properties.',
      );
    });
  });
});

/* ================================================================
 * Stage 3: Name & Save
 * ================================================================ */

describe('ActorDesigner — Stage 3: Name & Save', () => {
  async function goToStage3() {
    const user = userEvent.setup();
    renderDesigner();

    await user.click(screen.getByRole('button', { name: /continue/i }));
    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: {
        outputs: [
          { id: 'out-1', image_url: 'http://example.com/1.jpg', status: 'SUCCESS' },
          { id: 'out-2', image_url: 'http://example.com/2.jpg', status: 'SUCCESS' },
          { id: 'out-3', image_url: 'http://example.com/3.jpg', status: 'SUCCESS' },
          { id: 'out-4', image_url: 'http://example.com/4.jpg', status: 'SUCCESS' },
        ],
      },
    });

    for (let i = 0; i < 3; i++) {
      await user.click(screen.getByRole('button', { name: /generate/i }));
      await waitFor(() => {
        expect(screen.getByRole('button', { name: /confirm selection/i })).toBeInTheDocument();
      });
      const options = screen.getAllByRole('img', { name: /generated option/i });
      await user.click(options[0].closest('[class*="cursor-pointer"]') as HTMLElement);
      await user.click(screen.getByRole('button', { name: /confirm selection/i }));
    }

    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Name your actor and set properties.',
      );
    });

    return user;
  }

  it('shows the actor name input field', async () => {
    await goToStage3();
    expect(screen.getByLabelText(/actor name/i)).toBeInTheDocument();
  });

  it('shows the Back button to return to Stage 2', async () => {
    await goToStage3();
    expect(screen.getByRole('button', { name: /back/i })).toBeInTheDocument();
  });

  it('shows the Save Actor button', async () => {
    await goToStage3();
    expect(screen.getByRole('button', { name: /save actor/i })).toBeInTheDocument();
  });

  it('disables Save Actor when name is empty', async () => {
    await goToStage3();
    const saveButton = screen.getByRole('button', { name: /save actor/i });
    expect(saveButton).toBeDisabled();
  });

  it('enables Save Actor when name is entered', async () => {
    const user = await goToStage3();
    const nameInput = screen.getByLabelText(/actor name/i);
    await user.type(nameInput, 'Cyberpunk Woman');

    const saveButton = screen.getByRole('button', { name: /save actor/i });
    expect(saveButton).toBeEnabled();
  });

  it('calls PATCH /actors/:id on save', async () => {
    const user = await goToStage3();
    const nameInput = screen.getByLabelText(/actor name/i);
    await user.type(nameInput, 'Test Actor');

    (apiClient.patch as ReturnType<typeof vi.fn>).mockResolvedValue({ data: {} });

    await user.click(screen.getByRole('button', { name: /save actor/i }));

    await waitFor(() => {
      expect(apiClient.patch).toHaveBeenCalledWith(
        '/actors/actor-123',
        expect.objectContaining({ name: 'Test Actor' }),
      );
    });
  });

  it('navigates to actor page after successful save', async () => {
    const user = await goToStage3();
    const nameInput = screen.getByLabelText(/actor name/i);
    await user.type(nameInput, 'Test Actor');

    (apiClient.patch as ReturnType<typeof vi.fn>).mockResolvedValue({ data: {} });

    await user.click(screen.getByRole('button', { name: /save actor/i }));

    await waitFor(() => {
      expect(apiClient.patch).toHaveBeenCalled();
    });
  });

  it('shows Back button returns to Stage 2', async () => {
    const user = await goToStage3();
    await user.click(screen.getByRole('button', { name: /back/i }));

    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });
  });
});

/* ================================================================
 * Reference Photo Mode: Validation
 * ================================================================ */

describe('ActorDesigner — Reference Photo Mode: Validation', () => {
  it('shows validation error when trying to generate without prompt or images', async () => {
    const user = userEvent.setup();
    renderDesigner();

    // Select Reference Photo mode via label[for]
    const refLabel = document.querySelector('label[for="method-REFERENCE"]') as HTMLLabelElement;
    expect(refLabel).not.toBeNull();
    await user.click(refLabel);

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: { id: 'actor-ref-123' },
    });

    await user.click(screen.getByRole('button', { name: /continue/i }));

    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });

    const generateBtn = screen.getByRole('button', { name: /generate/i });
    await user.click(generateBtn);

    await waitFor(() => {
      expect(
        screen.getByText(/add a description or upload at least one reference image/i),
      ).toBeInTheDocument();
    });
  });

  it('clears validation error when user types a prompt', async () => {
    const user = userEvent.setup();
    renderDesigner();

    const refLabel2 = document.querySelector('label[for="method-REFERENCE"]') as HTMLLabelElement;
    await user.click(refLabel2);

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: { id: 'actor-ref-456' },
    });

    await user.click(screen.getByRole('button', { name: /continue/i }));

    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });

    await user.click(screen.getByRole('button', { name: /generate/i }));

    await waitFor(() => {
      expect(
        screen.getByText(/add a description or upload at least one reference image/i),
      ).toBeInTheDocument();
    });

    const promptField = screen.getByLabelText(/describe your actor/i);
    await user.type(promptField, 'A young woman');

    await waitFor(() => {
      expect(
        screen.queryByText(/add a description or upload at least one reference image/i),
      ).not.toBeInTheDocument();
    });
  });
});

/* ================================================================
 * Session Navigation
 * ================================================================ */

describe('ActorDesigner — Session Navigation', () => {
  it('does not show session navigator with only one session', async () => {
    const user = userEvent.setup();
    renderDesigner();

    await user.click(screen.getByRole('button', { name: /continue/i }));
    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });

    // No generation done → no session navigator visible
    expect(screen.queryByText(/session 1 of/i)).not.toBeInTheDocument();
  });

  it('shows session navigator after generating images', async () => {
    const user = userEvent.setup();
    renderDesigner();

    await user.click(screen.getByRole('button', { name: /continue/i }));
    await waitFor(() => {
      expect(screen.getByTestId('page-description')).toHaveTextContent(
        'Generate and select the best options for each layout.',
      );
    });

    (apiClient.post as ReturnType<typeof vi.fn>).mockResolvedValue({
      data: {
        outputs: [
          { id: 'out-1', image_url: 'http://example.com/1.jpg', status: 'SUCCESS' },
          { id: 'out-2', image_url: 'http://example.com/2.jpg', status: 'SUCCESS' },
          { id: 'out-3', image_url: 'http://example.com/3.jpg', status: 'SUCCESS' },
          { id: 'out-4', image_url: 'http://example.com/4.jpg', status: 'SUCCESS' },
        ],
      },
    });

    await user.click(screen.getByRole('button', { name: /generate/i }));

    await waitFor(() => {
      expect(screen.getByText(/session 1 of 1/i)).toBeInTheDocument();
    });
  });
});
